# Generated by Django 4.1.3 on 2022-11-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bday',
            field=models.DateField(verbose_name='bday'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tax_number',
            field=models.CharField(max_length=120, verbose_name='tax_number'),
        ),
    ]
