# Generated by Django 4.1.3 on 2022-11-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_bday_alter_user_tax_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bday',
            field=models.DateField(verbose_name='birthday'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tax_number',
            field=models.CharField(max_length=120, verbose_name='tax number'),
        ),
    ]
